# Generated by Django 5.1.4 on 2024-12-07 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedBrowser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser_name', models.CharField(choices=[('chrome', 'Chrome'), ('firefox', 'Firefox'), ('safari', 'Safari'), ('edge', 'Edge'), ('opera', 'Opera'), ('internet_explorer', 'Internet Explorer')], max_length=100, verbose_name='اسم المتصفح المحظور')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحظر')),
            ],
            options={
                'verbose_name': 'متصفح محظور',
                'verbose_name_plural': 'المتصفحات المحظورة',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=44, verbose_name='اسم الزائر')),
                ('session_id', models.CharField(max_length=255, unique=True, verbose_name='معرف الجلسة')),
                ('avatar', models.ImageField(blank=True, default='images/log.png', null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
            ],
            options={
                'verbose_name': 'زائر',
                'verbose_name_plural': 'الزوار',
            },
        ),
        migrations.CreateModel(
            name='Shildimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(upload_to='avatars/', verbose_name='الصور')),
            ],
            options={
                'verbose_name': 'صورة الدرع',
                'verbose_name_plural': 'صور الدروع',
            },
        ),
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='سبب الحظر')),
                ('banned_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحظر')),
                ('is_banned', models.BooleanField(default=True, verbose_name='محظور')),
                ('unban_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('banned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chatloop.customer', verbose_name='تم الحظر بواسطة')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatloop.customer', verbose_name='المستخدم المحظور')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatloop.guest', verbose_name='الزائر المحظور')),
            ],
            options={
                'verbose_name': 'حظر',
                'verbose_name_plural': 'الحظرات',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='غرفة الدردشة', max_length=100, verbose_name='اسم الغرفة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='رابط الغرفة')),
                ('customers', models.ManyToManyField(related_name='rooms', to='chatloop.customer', verbose_name='المستخدمين')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='محتوى الإشعار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإشعار')),
                ('is_read', models.BooleanField(default=False, verbose_name='تمت قراءته؟')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatloop.customer', verbose_name='المستخدم')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatloop.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='محتوى الرسالة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='صورة مرفقة')),
                ('emoji', models.CharField(blank=True, max_length=10, null=True, verbose_name='رمز تعبيري')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatloop.customer', verbose_name='المستخدم')),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatloop.guest', verbose_name='الزائر')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatloop.room', verbose_name='الغرفة')),
            ],
            options={
                'verbose_name': 'رسالة',
                'verbose_name_plural': 'الرسائل',
            },
        ),
        migrations.AddField(
            model_name='guest',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='chatloop.room', verbose_name='الغرفة'),
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='اسم الدرع')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shields', to='chatloop.customer', verbose_name='المستخدم')),
                ('Shield', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatloop.shildimages', verbose_name='صورة الدرع')),
            ],
            options={
                'verbose_name': 'درع',
                'verbose_name_plural': 'الدروع',
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('font_family', models.CharField(default='Arial', max_length=50, verbose_name='نوع الخط')),
                ('font_size', models.IntegerField(default=14, verbose_name='حجم الخط')),
                ('font_color', models.CharField(default='#000000', max_length=7, verbose_name='لون الخط')),
                ('background_color', models.CharField(default='#FFFFFF', max_length=7, verbose_name='لون الخلفية')),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='style', to='chatloop.customer', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'نمط',
                'verbose_name_plural': 'الأنماط',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='عضو مخفي')),
                ('is_ghost', models.BooleanField(default=False, verbose_name='عضو شبح')),
                ('can_see_hidden', models.BooleanField(default=True, verbose_name='من يمكنه رؤية العضو  المخفي')),
                ('can_see_ghost', models.BooleanField(default=True, verbose_name='من ممكن ان يرا العضو المخفي')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chatloop.customer', verbose_name='عضو')),
            ],
            options={
                'verbose_name': 'صلاحيه الاعضاء',
                'verbose_name_plural': 'صلاحية الاعضاء',
            },
        ),
    ]
