# Generated by Django 5.1.4 on 2024-12-08 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0006_directmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chatloop.message', verbose_name='الرسالة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chatloop.customer', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجابات',
                'unique_together': {('user', 'message')},
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chatloop.like', verbose_name='الإعجاب'),
        ),
    ]
