# Generated by Django 5.1.4 on 2024-12-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0018_alter_profilelike_liked_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_see_ghost',
            field=models.BooleanField(default=True, verbose_name='من ممكن ان يرا العضو الشبح'),
        ),
    ]
