# Generated by Django 5.1.4 on 2024-12-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0019_alter_userprofile_can_see_ghost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='can_see_ghost',
            field=models.BooleanField(default=False, verbose_name='من ممكن ان يرا العضو الشبح'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='can_see_hidden',
            field=models.BooleanField(default=False, verbose_name='من يمكنه رؤية العضو  المخفي'),
        ),
    ]
