# Generated by Django 5.1.4 on 2024-12-10 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0021_remove_userprofile_is_ghost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/', verbose_name='صورة مرفقة'),
        ),
    ]
