# Generated by Django 5.1.4 on 2024-12-08 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0008_userprofile_avatar_userprofile_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإعجاب')),
                ('liked_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='chatloop.userprofile', verbose_name='الملف الشخصي المعجب به')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_likes', to='chatloop.customer', verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إعجاب بالملف الشخصي',
                'verbose_name_plural': 'إعجابات الملفات الشخصية',
                'unique_together': {('user', 'liked_profile')},
            },
        ),
    ]
