# Generated by Django 5.1.4 on 2024-12-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0013_alter_directmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
