# Generated by Django 5.1.4 on 2024-12-09 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0015_privatemessagenotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatemessagenotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatloop.customer'),
        ),
    ]
