# Generated by Django 5.1.4 on 2024-12-09 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0016_alter_privatemessagenotification_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatemessagenotification',
            old_name='user',
            new_name='customer',
        ),
    ]
