# Generated by Django 5.1.4 on 2024-12-10 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0020_alter_userprofile_can_see_ghost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='is_ghost',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_hidden',
        ),
    ]
