# Generated by Django 5.1.4 on 2024-12-07 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_admin', models.BooleanField(default=False, verbose_name='مسؤول')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='عضو مخفي')),
                ('is_ghost', models.BooleanField(default=False, verbose_name='عضو شبح')),
                ('avatar', models.ImageField(blank=True, default='images/log.png', null=True, upload_to='avatars/', verbose_name='الصورة الشخصية')),
                ('notification_enabled', models.BooleanField(default=True, verbose_name='تفعيل الإشعارات')),
                ('join_date', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانضمام')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP الأخير')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
        ),
    ]
