# Generated by Django 5.1.4 on 2024-12-08 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0002_blockedbrowser_guest_shildimages_ban_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emoji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ban',
            name='banned_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bans', to='chatloop.customer', verbose_name='تم الحظر بواسطة'),
            preserve_default=False,
        ),
    ]
