# Generated by Django 5.1.4 on 2024-12-08 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0003_emoji_alter_ban_banned_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emoji',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chatloop.emoji', verbose_name='رمز تعبيري'),
        ),
    ]
