# Generated by Django 5.1.4 on 2024-12-08 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0004_alter_message_emoji'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='avatar',
            field=models.ImageField(blank=True, default='images/log.png', null=True, upload_to='avatars/', verbose_name='الصورة الشخصية'),
        ),
    ]
