# Generated by Django 5.1.4 on 2024-12-08 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0007_like_notification_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, default='images/log.png', null=True, upload_to='avatars/', verbose_name='الصورة الشخصية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='السيرة الذاتية'),
        ),
    ]
