# Generated by Django 5.1.4 on 2024-12-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0009_profilelike'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='تم حذفها؟'),
        ),
    ]
