# Generated by Django 5.1.4 on 2024-12-09 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0010_directmessage_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='guest_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to='chatloop.guest'),
        ),
    ]
