# Generated by Django 5.1.4 on 2024-12-09 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatloop', '0012_profilelike_guest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directmessage',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='chatloop.customer', verbose_name='المرسل'),
        ),
    ]
